/*
 * OData Service for namespace microsoft.graph
 *
 * This OData service is located at https://graph.microsoft.com/v1.0/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph
// MicrosoftGraphRatingJapanMoviesType the model 'MicrosoftGraphRatingJapanMoviesType'
type MicrosoftGraphRatingJapanMoviesType string

// List of microsoft.graph.ratingJapanMoviesType
const (
	ALL_ALLOWED MicrosoftGraphRatingJapanMoviesType = "allAllowed"
	ALL_BLOCKED MicrosoftGraphRatingJapanMoviesType = "allBlocked"
	GENERAL MicrosoftGraphRatingJapanMoviesType = "general"
	PARENTAL_GUIDANCE MicrosoftGraphRatingJapanMoviesType = "parentalGuidance"
	AGES_ABOVE15 MicrosoftGraphRatingJapanMoviesType = "agesAbove15"
	AGES_ABOVE18 MicrosoftGraphRatingJapanMoviesType = "agesAbove18"
)


