/*
 * OData Service for namespace microsoft.graph
 *
 * This OData service is located at https://graph.microsoft.com/v1.0/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph
import (
	"encoding/json"
)
// MicrosoftGraphItemAnalytics struct for MicrosoftGraphItemAnalytics
type MicrosoftGraphItemAnalytics struct {
	Id *string `json:"id,omitempty"`

	ItemActivityStats *[]MicrosoftGraphItemActivityStat `json:"itemActivityStats,omitempty"`

	AllTime *AnyOfmicrosoftGraphItemActivityStat `json:"allTime,omitempty"`
	isExplicitNullAllTime bool `json:"-"`
	LastSevenDays *AnyOfmicrosoftGraphItemActivityStat `json:"lastSevenDays,omitempty"`
	isExplicitNullLastSevenDays bool `json:"-"`
}

// GetId returns the Id field if non-nil, zero value otherwise.
func (o *MicrosoftGraphItemAnalytics) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphItemAnalytics) GetIdOk() (string, bool) {
	if o == nil || o.Id == nil {
		var ret string
		return ret, false
	}
	return *o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MicrosoftGraphItemAnalytics) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MicrosoftGraphItemAnalytics) SetId(v string) {
	o.Id = &v
}

// GetItemActivityStats returns the ItemActivityStats field if non-nil, zero value otherwise.
func (o *MicrosoftGraphItemAnalytics) GetItemActivityStats() []MicrosoftGraphItemActivityStat {
	if o == nil || o.ItemActivityStats == nil {
		var ret []MicrosoftGraphItemActivityStat
		return ret
	}
	return *o.ItemActivityStats
}

// GetItemActivityStatsOk returns a tuple with the ItemActivityStats field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphItemAnalytics) GetItemActivityStatsOk() ([]MicrosoftGraphItemActivityStat, bool) {
	if o == nil || o.ItemActivityStats == nil {
		var ret []MicrosoftGraphItemActivityStat
		return ret, false
	}
	return *o.ItemActivityStats, true
}

// HasItemActivityStats returns a boolean if a field has been set.
func (o *MicrosoftGraphItemAnalytics) HasItemActivityStats() bool {
	if o != nil && o.ItemActivityStats != nil {
		return true
	}

	return false
}

// SetItemActivityStats gets a reference to the given []MicrosoftGraphItemActivityStat and assigns it to the ItemActivityStats field.
func (o *MicrosoftGraphItemAnalytics) SetItemActivityStats(v []MicrosoftGraphItemActivityStat) {
	o.ItemActivityStats = &v
}

// GetAllTime returns the AllTime field if non-nil, zero value otherwise.
func (o *MicrosoftGraphItemAnalytics) GetAllTime() AnyOfmicrosoftGraphItemActivityStat {
	if o == nil || o.AllTime == nil {
		var ret AnyOfmicrosoftGraphItemActivityStat
		return ret
	}
	return *o.AllTime
}

// GetAllTimeOk returns a tuple with the AllTime field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphItemAnalytics) GetAllTimeOk() (AnyOfmicrosoftGraphItemActivityStat, bool) {
	if o == nil || o.AllTime == nil {
		var ret AnyOfmicrosoftGraphItemActivityStat
		return ret, false
	}
	return *o.AllTime, true
}

// HasAllTime returns a boolean if a field has been set.
func (o *MicrosoftGraphItemAnalytics) HasAllTime() bool {
	if o != nil && o.AllTime != nil {
		return true
	}

	return false
}

// SetAllTime gets a reference to the given AnyOfmicrosoftGraphItemActivityStat and assigns it to the AllTime field.
func (o *MicrosoftGraphItemAnalytics) SetAllTime(v AnyOfmicrosoftGraphItemActivityStat) {
	o.AllTime = &v
}

// SetAllTimeExplicitNull (un)sets AllTime to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The AllTime value is set to nil even if false is passed
func (o *MicrosoftGraphItemAnalytics) SetAllTimeExplicitNull(b bool) {
	o.AllTime = nil
	o.isExplicitNullAllTime = b
}
// GetLastSevenDays returns the LastSevenDays field if non-nil, zero value otherwise.
func (o *MicrosoftGraphItemAnalytics) GetLastSevenDays() AnyOfmicrosoftGraphItemActivityStat {
	if o == nil || o.LastSevenDays == nil {
		var ret AnyOfmicrosoftGraphItemActivityStat
		return ret
	}
	return *o.LastSevenDays
}

// GetLastSevenDaysOk returns a tuple with the LastSevenDays field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphItemAnalytics) GetLastSevenDaysOk() (AnyOfmicrosoftGraphItemActivityStat, bool) {
	if o == nil || o.LastSevenDays == nil {
		var ret AnyOfmicrosoftGraphItemActivityStat
		return ret, false
	}
	return *o.LastSevenDays, true
}

// HasLastSevenDays returns a boolean if a field has been set.
func (o *MicrosoftGraphItemAnalytics) HasLastSevenDays() bool {
	if o != nil && o.LastSevenDays != nil {
		return true
	}

	return false
}

// SetLastSevenDays gets a reference to the given AnyOfmicrosoftGraphItemActivityStat and assigns it to the LastSevenDays field.
func (o *MicrosoftGraphItemAnalytics) SetLastSevenDays(v AnyOfmicrosoftGraphItemActivityStat) {
	o.LastSevenDays = &v
}

// SetLastSevenDaysExplicitNull (un)sets LastSevenDays to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The LastSevenDays value is set to nil even if false is passed
func (o *MicrosoftGraphItemAnalytics) SetLastSevenDaysExplicitNull(b bool) {
	o.LastSevenDays = nil
	o.isExplicitNullLastSevenDays = b
}

// MarshalJSON returns the JSON representation of the model.
func (o MicrosoftGraphItemAnalytics) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.ItemActivityStats != nil {
		toSerialize["itemActivityStats"] = o.ItemActivityStats
	}
	if o.AllTime == nil {
		if o.isExplicitNullAllTime {
			toSerialize["allTime"] = o.AllTime
		}
	} else {
		toSerialize["allTime"] = o.AllTime
	}
	if o.LastSevenDays == nil {
		if o.isExplicitNullLastSevenDays {
			toSerialize["lastSevenDays"] = o.LastSevenDays
		}
	} else {
		toSerialize["lastSevenDays"] = o.LastSevenDays
	}
	return json.Marshal(toSerialize)
}


