/*
 * OData Service for namespace microsoft.graph
 *
 * This OData service is located at https://graph.microsoft.com/v1.0/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph
// MicrosoftGraphTeamsAppDistributionMethod the model 'MicrosoftGraphTeamsAppDistributionMethod'
type MicrosoftGraphTeamsAppDistributionMethod string

// List of microsoft.graph.teamsAppDistributionMethod
const (
	STORE MicrosoftGraphTeamsAppDistributionMethod = "store"
	ORGANIZATION MicrosoftGraphTeamsAppDistributionMethod = "organization"
	SIDELOADED MicrosoftGraphTeamsAppDistributionMethod = "sideloaded"
	UNKNOWN_FUTURE_VALUE MicrosoftGraphTeamsAppDistributionMethod = "unknownFutureValue"
)


