/*
 * OData Service for namespace microsoft.graph
 *
 * This OData service is located at https://graph.microsoft.com/v1.0/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph
import (
	"encoding/json"
)
// InlineObject1159 struct for InlineObject1159
type InlineObject1159 struct {
	Options *AnyOfmicrosoftGraphWorkbookWorksheetProtectionOptions `json:"options,omitempty"`
	isExplicitNullOptions bool `json:"-"`
}

// GetOptions returns the Options field if non-nil, zero value otherwise.
func (o *InlineObject1159) GetOptions() AnyOfmicrosoftGraphWorkbookWorksheetProtectionOptions {
	if o == nil || o.Options == nil {
		var ret AnyOfmicrosoftGraphWorkbookWorksheetProtectionOptions
		return ret
	}
	return *o.Options
}

// GetOptionsOk returns a tuple with the Options field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject1159) GetOptionsOk() (AnyOfmicrosoftGraphWorkbookWorksheetProtectionOptions, bool) {
	if o == nil || o.Options == nil {
		var ret AnyOfmicrosoftGraphWorkbookWorksheetProtectionOptions
		return ret, false
	}
	return *o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *InlineObject1159) HasOptions() bool {
	if o != nil && o.Options != nil {
		return true
	}

	return false
}

// SetOptions gets a reference to the given AnyOfmicrosoftGraphWorkbookWorksheetProtectionOptions and assigns it to the Options field.
func (o *InlineObject1159) SetOptions(v AnyOfmicrosoftGraphWorkbookWorksheetProtectionOptions) {
	o.Options = &v
}

// SetOptionsExplicitNull (un)sets Options to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The Options value is set to nil even if false is passed
func (o *InlineObject1159) SetOptionsExplicitNull(b bool) {
	o.Options = nil
	o.isExplicitNullOptions = b
}

// MarshalJSON returns the JSON representation of the model.
func (o InlineObject1159) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Options == nil {
		if o.isExplicitNullOptions {
			toSerialize["options"] = o.Options
		}
	} else {
		toSerialize["options"] = o.Options
	}
	return json.Marshal(toSerialize)
}


