/*
 * OData Service for namespace microsoft.graph
 *
 * This OData service is located at https://graph.microsoft.com/v1.0/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph
import (
	"encoding/json"
)
// InlineObject1014 struct for InlineObject1014
type InlineObject1014 struct {
	Array *AnyOfobject `json:"array,omitempty"`
	isExplicitNullArray bool `json:"-"`
	Quart *AnyOfobject `json:"quart,omitempty"`
	isExplicitNullQuart bool `json:"-"`
}

// GetArray returns the Array field if non-nil, zero value otherwise.
func (o *InlineObject1014) GetArray() AnyOfobject {
	if o == nil || o.Array == nil {
		var ret AnyOfobject
		return ret
	}
	return *o.Array
}

// GetArrayOk returns a tuple with the Array field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject1014) GetArrayOk() (AnyOfobject, bool) {
	if o == nil || o.Array == nil {
		var ret AnyOfobject
		return ret, false
	}
	return *o.Array, true
}

// HasArray returns a boolean if a field has been set.
func (o *InlineObject1014) HasArray() bool {
	if o != nil && o.Array != nil {
		return true
	}

	return false
}

// SetArray gets a reference to the given AnyOfobject and assigns it to the Array field.
func (o *InlineObject1014) SetArray(v AnyOfobject) {
	o.Array = &v
}

// SetArrayExplicitNull (un)sets Array to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The Array value is set to nil even if false is passed
func (o *InlineObject1014) SetArrayExplicitNull(b bool) {
	o.Array = nil
	o.isExplicitNullArray = b
}
// GetQuart returns the Quart field if non-nil, zero value otherwise.
func (o *InlineObject1014) GetQuart() AnyOfobject {
	if o == nil || o.Quart == nil {
		var ret AnyOfobject
		return ret
	}
	return *o.Quart
}

// GetQuartOk returns a tuple with the Quart field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject1014) GetQuartOk() (AnyOfobject, bool) {
	if o == nil || o.Quart == nil {
		var ret AnyOfobject
		return ret, false
	}
	return *o.Quart, true
}

// HasQuart returns a boolean if a field has been set.
func (o *InlineObject1014) HasQuart() bool {
	if o != nil && o.Quart != nil {
		return true
	}

	return false
}

// SetQuart gets a reference to the given AnyOfobject and assigns it to the Quart field.
func (o *InlineObject1014) SetQuart(v AnyOfobject) {
	o.Quart = &v
}

// SetQuartExplicitNull (un)sets Quart to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The Quart value is set to nil even if false is passed
func (o *InlineObject1014) SetQuartExplicitNull(b bool) {
	o.Quart = nil
	o.isExplicitNullQuart = b
}

// MarshalJSON returns the JSON representation of the model.
func (o InlineObject1014) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Array == nil {
		if o.isExplicitNullArray {
			toSerialize["array"] = o.Array
		}
	} else {
		toSerialize["array"] = o.Array
	}
	if o.Quart == nil {
		if o.isExplicitNullQuart {
			toSerialize["quart"] = o.Quart
		}
	} else {
		toSerialize["quart"] = o.Quart
	}
	return json.Marshal(toSerialize)
}


