/*
 * OData Service for namespace microsoft.graph
 *
 * This OData service is located at https://graph.microsoft.com/v1.0/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph
// MicrosoftGraphRecurrencePatternType the model 'MicrosoftGraphRecurrencePatternType'
type MicrosoftGraphRecurrencePatternType string

// List of microsoft.graph.recurrencePatternType
const (
	DAILY MicrosoftGraphRecurrencePatternType = "daily"
	WEEKLY MicrosoftGraphRecurrencePatternType = "weekly"
	ABSOLUTE_MONTHLY MicrosoftGraphRecurrencePatternType = "absoluteMonthly"
	RELATIVE_MONTHLY MicrosoftGraphRecurrencePatternType = "relativeMonthly"
	ABSOLUTE_YEARLY MicrosoftGraphRecurrencePatternType = "absoluteYearly"
	RELATIVE_YEARLY MicrosoftGraphRecurrencePatternType = "relativeYearly"
)


