/*
 * OData Service for namespace microsoft.graph
 *
 * This OData service is located at https://graph.microsoft.com/v1.0/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph
import (
	"encoding/json"
)
// InlineObject1006 struct for InlineObject1006
type InlineObject1006 struct {
	Number *AnyOfobject `json:"number,omitempty"`
	isExplicitNullNumber bool `json:"-"`
	Power *AnyOfobject `json:"power,omitempty"`
	isExplicitNullPower bool `json:"-"`
}

// GetNumber returns the Number field if non-nil, zero value otherwise.
func (o *InlineObject1006) GetNumber() AnyOfobject {
	if o == nil || o.Number == nil {
		var ret AnyOfobject
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject1006) GetNumberOk() (AnyOfobject, bool) {
	if o == nil || o.Number == nil {
		var ret AnyOfobject
		return ret, false
	}
	return *o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *InlineObject1006) HasNumber() bool {
	if o != nil && o.Number != nil {
		return true
	}

	return false
}

// SetNumber gets a reference to the given AnyOfobject and assigns it to the Number field.
func (o *InlineObject1006) SetNumber(v AnyOfobject) {
	o.Number = &v
}

// SetNumberExplicitNull (un)sets Number to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The Number value is set to nil even if false is passed
func (o *InlineObject1006) SetNumberExplicitNull(b bool) {
	o.Number = nil
	o.isExplicitNullNumber = b
}
// GetPower returns the Power field if non-nil, zero value otherwise.
func (o *InlineObject1006) GetPower() AnyOfobject {
	if o == nil || o.Power == nil {
		var ret AnyOfobject
		return ret
	}
	return *o.Power
}

// GetPowerOk returns a tuple with the Power field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject1006) GetPowerOk() (AnyOfobject, bool) {
	if o == nil || o.Power == nil {
		var ret AnyOfobject
		return ret, false
	}
	return *o.Power, true
}

// HasPower returns a boolean if a field has been set.
func (o *InlineObject1006) HasPower() bool {
	if o != nil && o.Power != nil {
		return true
	}

	return false
}

// SetPower gets a reference to the given AnyOfobject and assigns it to the Power field.
func (o *InlineObject1006) SetPower(v AnyOfobject) {
	o.Power = &v
}

// SetPowerExplicitNull (un)sets Power to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The Power value is set to nil even if false is passed
func (o *InlineObject1006) SetPowerExplicitNull(b bool) {
	o.Power = nil
	o.isExplicitNullPower = b
}

// MarshalJSON returns the JSON representation of the model.
func (o InlineObject1006) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Number == nil {
		if o.isExplicitNullNumber {
			toSerialize["number"] = o.Number
		}
	} else {
		toSerialize["number"] = o.Number
	}
	if o.Power == nil {
		if o.isExplicitNullPower {
			toSerialize["power"] = o.Power
		}
	} else {
		toSerialize["power"] = o.Power
	}
	return json.Marshal(toSerialize)
}


