/*
 * OData Service for namespace microsoft.graph
 *
 * This OData service is located at https://graph.microsoft.com/v1.0/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph
import (
	"encoding/json"
)
// MicrosoftGraphProvisionedPlan struct for MicrosoftGraphProvisionedPlan
type MicrosoftGraphProvisionedPlan struct {
	CapabilityStatus *string `json:"capabilityStatus,omitempty"`
	isExplicitNullCapabilityStatus bool `json:"-"`
	ProvisioningStatus *string `json:"provisioningStatus,omitempty"`
	isExplicitNullProvisioningStatus bool `json:"-"`
	Service *string `json:"service,omitempty"`
	isExplicitNullService bool `json:"-"`
}

// GetCapabilityStatus returns the CapabilityStatus field if non-nil, zero value otherwise.
func (o *MicrosoftGraphProvisionedPlan) GetCapabilityStatus() string {
	if o == nil || o.CapabilityStatus == nil {
		var ret string
		return ret
	}
	return *o.CapabilityStatus
}

// GetCapabilityStatusOk returns a tuple with the CapabilityStatus field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphProvisionedPlan) GetCapabilityStatusOk() (string, bool) {
	if o == nil || o.CapabilityStatus == nil {
		var ret string
		return ret, false
	}
	return *o.CapabilityStatus, true
}

// HasCapabilityStatus returns a boolean if a field has been set.
func (o *MicrosoftGraphProvisionedPlan) HasCapabilityStatus() bool {
	if o != nil && o.CapabilityStatus != nil {
		return true
	}

	return false
}

// SetCapabilityStatus gets a reference to the given string and assigns it to the CapabilityStatus field.
func (o *MicrosoftGraphProvisionedPlan) SetCapabilityStatus(v string) {
	o.CapabilityStatus = &v
}

// SetCapabilityStatusExplicitNull (un)sets CapabilityStatus to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The CapabilityStatus value is set to nil even if false is passed
func (o *MicrosoftGraphProvisionedPlan) SetCapabilityStatusExplicitNull(b bool) {
	o.CapabilityStatus = nil
	o.isExplicitNullCapabilityStatus = b
}
// GetProvisioningStatus returns the ProvisioningStatus field if non-nil, zero value otherwise.
func (o *MicrosoftGraphProvisionedPlan) GetProvisioningStatus() string {
	if o == nil || o.ProvisioningStatus == nil {
		var ret string
		return ret
	}
	return *o.ProvisioningStatus
}

// GetProvisioningStatusOk returns a tuple with the ProvisioningStatus field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphProvisionedPlan) GetProvisioningStatusOk() (string, bool) {
	if o == nil || o.ProvisioningStatus == nil {
		var ret string
		return ret, false
	}
	return *o.ProvisioningStatus, true
}

// HasProvisioningStatus returns a boolean if a field has been set.
func (o *MicrosoftGraphProvisionedPlan) HasProvisioningStatus() bool {
	if o != nil && o.ProvisioningStatus != nil {
		return true
	}

	return false
}

// SetProvisioningStatus gets a reference to the given string and assigns it to the ProvisioningStatus field.
func (o *MicrosoftGraphProvisionedPlan) SetProvisioningStatus(v string) {
	o.ProvisioningStatus = &v
}

// SetProvisioningStatusExplicitNull (un)sets ProvisioningStatus to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The ProvisioningStatus value is set to nil even if false is passed
func (o *MicrosoftGraphProvisionedPlan) SetProvisioningStatusExplicitNull(b bool) {
	o.ProvisioningStatus = nil
	o.isExplicitNullProvisioningStatus = b
}
// GetService returns the Service field if non-nil, zero value otherwise.
func (o *MicrosoftGraphProvisionedPlan) GetService() string {
	if o == nil || o.Service == nil {
		var ret string
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphProvisionedPlan) GetServiceOk() (string, bool) {
	if o == nil || o.Service == nil {
		var ret string
		return ret, false
	}
	return *o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *MicrosoftGraphProvisionedPlan) HasService() bool {
	if o != nil && o.Service != nil {
		return true
	}

	return false
}

// SetService gets a reference to the given string and assigns it to the Service field.
func (o *MicrosoftGraphProvisionedPlan) SetService(v string) {
	o.Service = &v
}

// SetServiceExplicitNull (un)sets Service to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The Service value is set to nil even if false is passed
func (o *MicrosoftGraphProvisionedPlan) SetServiceExplicitNull(b bool) {
	o.Service = nil
	o.isExplicitNullService = b
}

// MarshalJSON returns the JSON representation of the model.
func (o MicrosoftGraphProvisionedPlan) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CapabilityStatus == nil {
		if o.isExplicitNullCapabilityStatus {
			toSerialize["capabilityStatus"] = o.CapabilityStatus
		}
	} else {
		toSerialize["capabilityStatus"] = o.CapabilityStatus
	}
	if o.ProvisioningStatus == nil {
		if o.isExplicitNullProvisioningStatus {
			toSerialize["provisioningStatus"] = o.ProvisioningStatus
		}
	} else {
		toSerialize["provisioningStatus"] = o.ProvisioningStatus
	}
	if o.Service == nil {
		if o.isExplicitNullService {
			toSerialize["service"] = o.Service
		}
	} else {
		toSerialize["service"] = o.Service
	}
	return json.Marshal(toSerialize)
}


