/*
 * OData Service for namespace microsoft.graph
 *
 * This OData service is located at https://graph.microsoft.com/v1.0/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph
import (
	"encoding/json"
)
// MicrosoftGraphContactFolder struct for MicrosoftGraphContactFolder
type MicrosoftGraphContactFolder struct {
	Id *string `json:"id,omitempty"`

	ParentFolderId *string `json:"parentFolderId,omitempty"`
	isExplicitNullParentFolderId bool `json:"-"`
	DisplayName *string `json:"displayName,omitempty"`
	isExplicitNullDisplayName bool `json:"-"`
	SingleValueExtendedProperties *[]MicrosoftGraphSingleValueLegacyExtendedProperty `json:"singleValueExtendedProperties,omitempty"`

	MultiValueExtendedProperties *[]MicrosoftGraphMultiValueLegacyExtendedProperty `json:"multiValueExtendedProperties,omitempty"`

	Contacts *[]MicrosoftGraphContact `json:"contacts,omitempty"`

	ChildFolders *[]MicrosoftGraphContactFolder `json:"childFolders,omitempty"`

}

// GetId returns the Id field if non-nil, zero value otherwise.
func (o *MicrosoftGraphContactFolder) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphContactFolder) GetIdOk() (string, bool) {
	if o == nil || o.Id == nil {
		var ret string
		return ret, false
	}
	return *o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MicrosoftGraphContactFolder) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MicrosoftGraphContactFolder) SetId(v string) {
	o.Id = &v
}

// GetParentFolderId returns the ParentFolderId field if non-nil, zero value otherwise.
func (o *MicrosoftGraphContactFolder) GetParentFolderId() string {
	if o == nil || o.ParentFolderId == nil {
		var ret string
		return ret
	}
	return *o.ParentFolderId
}

// GetParentFolderIdOk returns a tuple with the ParentFolderId field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphContactFolder) GetParentFolderIdOk() (string, bool) {
	if o == nil || o.ParentFolderId == nil {
		var ret string
		return ret, false
	}
	return *o.ParentFolderId, true
}

// HasParentFolderId returns a boolean if a field has been set.
func (o *MicrosoftGraphContactFolder) HasParentFolderId() bool {
	if o != nil && o.ParentFolderId != nil {
		return true
	}

	return false
}

// SetParentFolderId gets a reference to the given string and assigns it to the ParentFolderId field.
func (o *MicrosoftGraphContactFolder) SetParentFolderId(v string) {
	o.ParentFolderId = &v
}

// SetParentFolderIdExplicitNull (un)sets ParentFolderId to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The ParentFolderId value is set to nil even if false is passed
func (o *MicrosoftGraphContactFolder) SetParentFolderIdExplicitNull(b bool) {
	o.ParentFolderId = nil
	o.isExplicitNullParentFolderId = b
}
// GetDisplayName returns the DisplayName field if non-nil, zero value otherwise.
func (o *MicrosoftGraphContactFolder) GetDisplayName() string {
	if o == nil || o.DisplayName == nil {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphContactFolder) GetDisplayNameOk() (string, bool) {
	if o == nil || o.DisplayName == nil {
		var ret string
		return ret, false
	}
	return *o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *MicrosoftGraphContactFolder) HasDisplayName() bool {
	if o != nil && o.DisplayName != nil {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *MicrosoftGraphContactFolder) SetDisplayName(v string) {
	o.DisplayName = &v
}

// SetDisplayNameExplicitNull (un)sets DisplayName to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The DisplayName value is set to nil even if false is passed
func (o *MicrosoftGraphContactFolder) SetDisplayNameExplicitNull(b bool) {
	o.DisplayName = nil
	o.isExplicitNullDisplayName = b
}
// GetSingleValueExtendedProperties returns the SingleValueExtendedProperties field if non-nil, zero value otherwise.
func (o *MicrosoftGraphContactFolder) GetSingleValueExtendedProperties() []MicrosoftGraphSingleValueLegacyExtendedProperty {
	if o == nil || o.SingleValueExtendedProperties == nil {
		var ret []MicrosoftGraphSingleValueLegacyExtendedProperty
		return ret
	}
	return *o.SingleValueExtendedProperties
}

// GetSingleValueExtendedPropertiesOk returns a tuple with the SingleValueExtendedProperties field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphContactFolder) GetSingleValueExtendedPropertiesOk() ([]MicrosoftGraphSingleValueLegacyExtendedProperty, bool) {
	if o == nil || o.SingleValueExtendedProperties == nil {
		var ret []MicrosoftGraphSingleValueLegacyExtendedProperty
		return ret, false
	}
	return *o.SingleValueExtendedProperties, true
}

// HasSingleValueExtendedProperties returns a boolean if a field has been set.
func (o *MicrosoftGraphContactFolder) HasSingleValueExtendedProperties() bool {
	if o != nil && o.SingleValueExtendedProperties != nil {
		return true
	}

	return false
}

// SetSingleValueExtendedProperties gets a reference to the given []MicrosoftGraphSingleValueLegacyExtendedProperty and assigns it to the SingleValueExtendedProperties field.
func (o *MicrosoftGraphContactFolder) SetSingleValueExtendedProperties(v []MicrosoftGraphSingleValueLegacyExtendedProperty) {
	o.SingleValueExtendedProperties = &v
}

// GetMultiValueExtendedProperties returns the MultiValueExtendedProperties field if non-nil, zero value otherwise.
func (o *MicrosoftGraphContactFolder) GetMultiValueExtendedProperties() []MicrosoftGraphMultiValueLegacyExtendedProperty {
	if o == nil || o.MultiValueExtendedProperties == nil {
		var ret []MicrosoftGraphMultiValueLegacyExtendedProperty
		return ret
	}
	return *o.MultiValueExtendedProperties
}

// GetMultiValueExtendedPropertiesOk returns a tuple with the MultiValueExtendedProperties field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphContactFolder) GetMultiValueExtendedPropertiesOk() ([]MicrosoftGraphMultiValueLegacyExtendedProperty, bool) {
	if o == nil || o.MultiValueExtendedProperties == nil {
		var ret []MicrosoftGraphMultiValueLegacyExtendedProperty
		return ret, false
	}
	return *o.MultiValueExtendedProperties, true
}

// HasMultiValueExtendedProperties returns a boolean if a field has been set.
func (o *MicrosoftGraphContactFolder) HasMultiValueExtendedProperties() bool {
	if o != nil && o.MultiValueExtendedProperties != nil {
		return true
	}

	return false
}

// SetMultiValueExtendedProperties gets a reference to the given []MicrosoftGraphMultiValueLegacyExtendedProperty and assigns it to the MultiValueExtendedProperties field.
func (o *MicrosoftGraphContactFolder) SetMultiValueExtendedProperties(v []MicrosoftGraphMultiValueLegacyExtendedProperty) {
	o.MultiValueExtendedProperties = &v
}

// GetContacts returns the Contacts field if non-nil, zero value otherwise.
func (o *MicrosoftGraphContactFolder) GetContacts() []MicrosoftGraphContact {
	if o == nil || o.Contacts == nil {
		var ret []MicrosoftGraphContact
		return ret
	}
	return *o.Contacts
}

// GetContactsOk returns a tuple with the Contacts field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphContactFolder) GetContactsOk() ([]MicrosoftGraphContact, bool) {
	if o == nil || o.Contacts == nil {
		var ret []MicrosoftGraphContact
		return ret, false
	}
	return *o.Contacts, true
}

// HasContacts returns a boolean if a field has been set.
func (o *MicrosoftGraphContactFolder) HasContacts() bool {
	if o != nil && o.Contacts != nil {
		return true
	}

	return false
}

// SetContacts gets a reference to the given []MicrosoftGraphContact and assigns it to the Contacts field.
func (o *MicrosoftGraphContactFolder) SetContacts(v []MicrosoftGraphContact) {
	o.Contacts = &v
}

// GetChildFolders returns the ChildFolders field if non-nil, zero value otherwise.
func (o *MicrosoftGraphContactFolder) GetChildFolders() []MicrosoftGraphContactFolder {
	if o == nil || o.ChildFolders == nil {
		var ret []MicrosoftGraphContactFolder
		return ret
	}
	return *o.ChildFolders
}

// GetChildFoldersOk returns a tuple with the ChildFolders field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphContactFolder) GetChildFoldersOk() ([]MicrosoftGraphContactFolder, bool) {
	if o == nil || o.ChildFolders == nil {
		var ret []MicrosoftGraphContactFolder
		return ret, false
	}
	return *o.ChildFolders, true
}

// HasChildFolders returns a boolean if a field has been set.
func (o *MicrosoftGraphContactFolder) HasChildFolders() bool {
	if o != nil && o.ChildFolders != nil {
		return true
	}

	return false
}

// SetChildFolders gets a reference to the given []MicrosoftGraphContactFolder and assigns it to the ChildFolders field.
func (o *MicrosoftGraphContactFolder) SetChildFolders(v []MicrosoftGraphContactFolder) {
	o.ChildFolders = &v
}


// MarshalJSON returns the JSON representation of the model.
func (o MicrosoftGraphContactFolder) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.ParentFolderId == nil {
		if o.isExplicitNullParentFolderId {
			toSerialize["parentFolderId"] = o.ParentFolderId
		}
	} else {
		toSerialize["parentFolderId"] = o.ParentFolderId
	}
	if o.DisplayName == nil {
		if o.isExplicitNullDisplayName {
			toSerialize["displayName"] = o.DisplayName
		}
	} else {
		toSerialize["displayName"] = o.DisplayName
	}
	if o.SingleValueExtendedProperties != nil {
		toSerialize["singleValueExtendedProperties"] = o.SingleValueExtendedProperties
	}
	if o.MultiValueExtendedProperties != nil {
		toSerialize["multiValueExtendedProperties"] = o.MultiValueExtendedProperties
	}
	if o.Contacts != nil {
		toSerialize["contacts"] = o.Contacts
	}
	if o.ChildFolders != nil {
		toSerialize["childFolders"] = o.ChildFolders
	}
	return json.Marshal(toSerialize)
}


