/*
 * OData Service for namespace microsoft.graph
 *
 * This OData service is located at https://graph.microsoft.com/v1.0/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph
import (
	"encoding/json"
)
// MicrosoftGraphHostSecurityState struct for MicrosoftGraphHostSecurityState
type MicrosoftGraphHostSecurityState struct {
	Fqdn *string `json:"fqdn,omitempty"`
	isExplicitNullFqdn bool `json:"-"`
	IsAzureAdJoined *bool `json:"isAzureAdJoined,omitempty"`
	isExplicitNullIsAzureAdJoined bool `json:"-"`
	IsAzureAdRegistered *bool `json:"isAzureAdRegistered,omitempty"`
	isExplicitNullIsAzureAdRegistered bool `json:"-"`
	IsHybridAzureDomainJoined *bool `json:"isHybridAzureDomainJoined,omitempty"`
	isExplicitNullIsHybridAzureDomainJoined bool `json:"-"`
	NetBiosName *string `json:"netBiosName,omitempty"`
	isExplicitNullNetBiosName bool `json:"-"`
	Os *string `json:"os,omitempty"`
	isExplicitNullOs bool `json:"-"`
	PrivateIpAddress *string `json:"privateIpAddress,omitempty"`
	isExplicitNullPrivateIpAddress bool `json:"-"`
	PublicIpAddress *string `json:"publicIpAddress,omitempty"`
	isExplicitNullPublicIpAddress bool `json:"-"`
	RiskScore *string `json:"riskScore,omitempty"`
	isExplicitNullRiskScore bool `json:"-"`
}

// GetFqdn returns the Fqdn field if non-nil, zero value otherwise.
func (o *MicrosoftGraphHostSecurityState) GetFqdn() string {
	if o == nil || o.Fqdn == nil {
		var ret string
		return ret
	}
	return *o.Fqdn
}

// GetFqdnOk returns a tuple with the Fqdn field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphHostSecurityState) GetFqdnOk() (string, bool) {
	if o == nil || o.Fqdn == nil {
		var ret string
		return ret, false
	}
	return *o.Fqdn, true
}

// HasFqdn returns a boolean if a field has been set.
func (o *MicrosoftGraphHostSecurityState) HasFqdn() bool {
	if o != nil && o.Fqdn != nil {
		return true
	}

	return false
}

// SetFqdn gets a reference to the given string and assigns it to the Fqdn field.
func (o *MicrosoftGraphHostSecurityState) SetFqdn(v string) {
	o.Fqdn = &v
}

// SetFqdnExplicitNull (un)sets Fqdn to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The Fqdn value is set to nil even if false is passed
func (o *MicrosoftGraphHostSecurityState) SetFqdnExplicitNull(b bool) {
	o.Fqdn = nil
	o.isExplicitNullFqdn = b
}
// GetIsAzureAdJoined returns the IsAzureAdJoined field if non-nil, zero value otherwise.
func (o *MicrosoftGraphHostSecurityState) GetIsAzureAdJoined() bool {
	if o == nil || o.IsAzureAdJoined == nil {
		var ret bool
		return ret
	}
	return *o.IsAzureAdJoined
}

// GetIsAzureAdJoinedOk returns a tuple with the IsAzureAdJoined field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphHostSecurityState) GetIsAzureAdJoinedOk() (bool, bool) {
	if o == nil || o.IsAzureAdJoined == nil {
		var ret bool
		return ret, false
	}
	return *o.IsAzureAdJoined, true
}

// HasIsAzureAdJoined returns a boolean if a field has been set.
func (o *MicrosoftGraphHostSecurityState) HasIsAzureAdJoined() bool {
	if o != nil && o.IsAzureAdJoined != nil {
		return true
	}

	return false
}

// SetIsAzureAdJoined gets a reference to the given bool and assigns it to the IsAzureAdJoined field.
func (o *MicrosoftGraphHostSecurityState) SetIsAzureAdJoined(v bool) {
	o.IsAzureAdJoined = &v
}

// SetIsAzureAdJoinedExplicitNull (un)sets IsAzureAdJoined to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The IsAzureAdJoined value is set to nil even if false is passed
func (o *MicrosoftGraphHostSecurityState) SetIsAzureAdJoinedExplicitNull(b bool) {
	o.IsAzureAdJoined = nil
	o.isExplicitNullIsAzureAdJoined = b
}
// GetIsAzureAdRegistered returns the IsAzureAdRegistered field if non-nil, zero value otherwise.
func (o *MicrosoftGraphHostSecurityState) GetIsAzureAdRegistered() bool {
	if o == nil || o.IsAzureAdRegistered == nil {
		var ret bool
		return ret
	}
	return *o.IsAzureAdRegistered
}

// GetIsAzureAdRegisteredOk returns a tuple with the IsAzureAdRegistered field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphHostSecurityState) GetIsAzureAdRegisteredOk() (bool, bool) {
	if o == nil || o.IsAzureAdRegistered == nil {
		var ret bool
		return ret, false
	}
	return *o.IsAzureAdRegistered, true
}

// HasIsAzureAdRegistered returns a boolean if a field has been set.
func (o *MicrosoftGraphHostSecurityState) HasIsAzureAdRegistered() bool {
	if o != nil && o.IsAzureAdRegistered != nil {
		return true
	}

	return false
}

// SetIsAzureAdRegistered gets a reference to the given bool and assigns it to the IsAzureAdRegistered field.
func (o *MicrosoftGraphHostSecurityState) SetIsAzureAdRegistered(v bool) {
	o.IsAzureAdRegistered = &v
}

// SetIsAzureAdRegisteredExplicitNull (un)sets IsAzureAdRegistered to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The IsAzureAdRegistered value is set to nil even if false is passed
func (o *MicrosoftGraphHostSecurityState) SetIsAzureAdRegisteredExplicitNull(b bool) {
	o.IsAzureAdRegistered = nil
	o.isExplicitNullIsAzureAdRegistered = b
}
// GetIsHybridAzureDomainJoined returns the IsHybridAzureDomainJoined field if non-nil, zero value otherwise.
func (o *MicrosoftGraphHostSecurityState) GetIsHybridAzureDomainJoined() bool {
	if o == nil || o.IsHybridAzureDomainJoined == nil {
		var ret bool
		return ret
	}
	return *o.IsHybridAzureDomainJoined
}

// GetIsHybridAzureDomainJoinedOk returns a tuple with the IsHybridAzureDomainJoined field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphHostSecurityState) GetIsHybridAzureDomainJoinedOk() (bool, bool) {
	if o == nil || o.IsHybridAzureDomainJoined == nil {
		var ret bool
		return ret, false
	}
	return *o.IsHybridAzureDomainJoined, true
}

// HasIsHybridAzureDomainJoined returns a boolean if a field has been set.
func (o *MicrosoftGraphHostSecurityState) HasIsHybridAzureDomainJoined() bool {
	if o != nil && o.IsHybridAzureDomainJoined != nil {
		return true
	}

	return false
}

// SetIsHybridAzureDomainJoined gets a reference to the given bool and assigns it to the IsHybridAzureDomainJoined field.
func (o *MicrosoftGraphHostSecurityState) SetIsHybridAzureDomainJoined(v bool) {
	o.IsHybridAzureDomainJoined = &v
}

// SetIsHybridAzureDomainJoinedExplicitNull (un)sets IsHybridAzureDomainJoined to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The IsHybridAzureDomainJoined value is set to nil even if false is passed
func (o *MicrosoftGraphHostSecurityState) SetIsHybridAzureDomainJoinedExplicitNull(b bool) {
	o.IsHybridAzureDomainJoined = nil
	o.isExplicitNullIsHybridAzureDomainJoined = b
}
// GetNetBiosName returns the NetBiosName field if non-nil, zero value otherwise.
func (o *MicrosoftGraphHostSecurityState) GetNetBiosName() string {
	if o == nil || o.NetBiosName == nil {
		var ret string
		return ret
	}
	return *o.NetBiosName
}

// GetNetBiosNameOk returns a tuple with the NetBiosName field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphHostSecurityState) GetNetBiosNameOk() (string, bool) {
	if o == nil || o.NetBiosName == nil {
		var ret string
		return ret, false
	}
	return *o.NetBiosName, true
}

// HasNetBiosName returns a boolean if a field has been set.
func (o *MicrosoftGraphHostSecurityState) HasNetBiosName() bool {
	if o != nil && o.NetBiosName != nil {
		return true
	}

	return false
}

// SetNetBiosName gets a reference to the given string and assigns it to the NetBiosName field.
func (o *MicrosoftGraphHostSecurityState) SetNetBiosName(v string) {
	o.NetBiosName = &v
}

// SetNetBiosNameExplicitNull (un)sets NetBiosName to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The NetBiosName value is set to nil even if false is passed
func (o *MicrosoftGraphHostSecurityState) SetNetBiosNameExplicitNull(b bool) {
	o.NetBiosName = nil
	o.isExplicitNullNetBiosName = b
}
// GetOs returns the Os field if non-nil, zero value otherwise.
func (o *MicrosoftGraphHostSecurityState) GetOs() string {
	if o == nil || o.Os == nil {
		var ret string
		return ret
	}
	return *o.Os
}

// GetOsOk returns a tuple with the Os field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphHostSecurityState) GetOsOk() (string, bool) {
	if o == nil || o.Os == nil {
		var ret string
		return ret, false
	}
	return *o.Os, true
}

// HasOs returns a boolean if a field has been set.
func (o *MicrosoftGraphHostSecurityState) HasOs() bool {
	if o != nil && o.Os != nil {
		return true
	}

	return false
}

// SetOs gets a reference to the given string and assigns it to the Os field.
func (o *MicrosoftGraphHostSecurityState) SetOs(v string) {
	o.Os = &v
}

// SetOsExplicitNull (un)sets Os to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The Os value is set to nil even if false is passed
func (o *MicrosoftGraphHostSecurityState) SetOsExplicitNull(b bool) {
	o.Os = nil
	o.isExplicitNullOs = b
}
// GetPrivateIpAddress returns the PrivateIpAddress field if non-nil, zero value otherwise.
func (o *MicrosoftGraphHostSecurityState) GetPrivateIpAddress() string {
	if o == nil || o.PrivateIpAddress == nil {
		var ret string
		return ret
	}
	return *o.PrivateIpAddress
}

// GetPrivateIpAddressOk returns a tuple with the PrivateIpAddress field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphHostSecurityState) GetPrivateIpAddressOk() (string, bool) {
	if o == nil || o.PrivateIpAddress == nil {
		var ret string
		return ret, false
	}
	return *o.PrivateIpAddress, true
}

// HasPrivateIpAddress returns a boolean if a field has been set.
func (o *MicrosoftGraphHostSecurityState) HasPrivateIpAddress() bool {
	if o != nil && o.PrivateIpAddress != nil {
		return true
	}

	return false
}

// SetPrivateIpAddress gets a reference to the given string and assigns it to the PrivateIpAddress field.
func (o *MicrosoftGraphHostSecurityState) SetPrivateIpAddress(v string) {
	o.PrivateIpAddress = &v
}

// SetPrivateIpAddressExplicitNull (un)sets PrivateIpAddress to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The PrivateIpAddress value is set to nil even if false is passed
func (o *MicrosoftGraphHostSecurityState) SetPrivateIpAddressExplicitNull(b bool) {
	o.PrivateIpAddress = nil
	o.isExplicitNullPrivateIpAddress = b
}
// GetPublicIpAddress returns the PublicIpAddress field if non-nil, zero value otherwise.
func (o *MicrosoftGraphHostSecurityState) GetPublicIpAddress() string {
	if o == nil || o.PublicIpAddress == nil {
		var ret string
		return ret
	}
	return *o.PublicIpAddress
}

// GetPublicIpAddressOk returns a tuple with the PublicIpAddress field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphHostSecurityState) GetPublicIpAddressOk() (string, bool) {
	if o == nil || o.PublicIpAddress == nil {
		var ret string
		return ret, false
	}
	return *o.PublicIpAddress, true
}

// HasPublicIpAddress returns a boolean if a field has been set.
func (o *MicrosoftGraphHostSecurityState) HasPublicIpAddress() bool {
	if o != nil && o.PublicIpAddress != nil {
		return true
	}

	return false
}

// SetPublicIpAddress gets a reference to the given string and assigns it to the PublicIpAddress field.
func (o *MicrosoftGraphHostSecurityState) SetPublicIpAddress(v string) {
	o.PublicIpAddress = &v
}

// SetPublicIpAddressExplicitNull (un)sets PublicIpAddress to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The PublicIpAddress value is set to nil even if false is passed
func (o *MicrosoftGraphHostSecurityState) SetPublicIpAddressExplicitNull(b bool) {
	o.PublicIpAddress = nil
	o.isExplicitNullPublicIpAddress = b
}
// GetRiskScore returns the RiskScore field if non-nil, zero value otherwise.
func (o *MicrosoftGraphHostSecurityState) GetRiskScore() string {
	if o == nil || o.RiskScore == nil {
		var ret string
		return ret
	}
	return *o.RiskScore
}

// GetRiskScoreOk returns a tuple with the RiskScore field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphHostSecurityState) GetRiskScoreOk() (string, bool) {
	if o == nil || o.RiskScore == nil {
		var ret string
		return ret, false
	}
	return *o.RiskScore, true
}

// HasRiskScore returns a boolean if a field has been set.
func (o *MicrosoftGraphHostSecurityState) HasRiskScore() bool {
	if o != nil && o.RiskScore != nil {
		return true
	}

	return false
}

// SetRiskScore gets a reference to the given string and assigns it to the RiskScore field.
func (o *MicrosoftGraphHostSecurityState) SetRiskScore(v string) {
	o.RiskScore = &v
}

// SetRiskScoreExplicitNull (un)sets RiskScore to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The RiskScore value is set to nil even if false is passed
func (o *MicrosoftGraphHostSecurityState) SetRiskScoreExplicitNull(b bool) {
	o.RiskScore = nil
	o.isExplicitNullRiskScore = b
}

// MarshalJSON returns the JSON representation of the model.
func (o MicrosoftGraphHostSecurityState) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Fqdn == nil {
		if o.isExplicitNullFqdn {
			toSerialize["fqdn"] = o.Fqdn
		}
	} else {
		toSerialize["fqdn"] = o.Fqdn
	}
	if o.IsAzureAdJoined == nil {
		if o.isExplicitNullIsAzureAdJoined {
			toSerialize["isAzureAdJoined"] = o.IsAzureAdJoined
		}
	} else {
		toSerialize["isAzureAdJoined"] = o.IsAzureAdJoined
	}
	if o.IsAzureAdRegistered == nil {
		if o.isExplicitNullIsAzureAdRegistered {
			toSerialize["isAzureAdRegistered"] = o.IsAzureAdRegistered
		}
	} else {
		toSerialize["isAzureAdRegistered"] = o.IsAzureAdRegistered
	}
	if o.IsHybridAzureDomainJoined == nil {
		if o.isExplicitNullIsHybridAzureDomainJoined {
			toSerialize["isHybridAzureDomainJoined"] = o.IsHybridAzureDomainJoined
		}
	} else {
		toSerialize["isHybridAzureDomainJoined"] = o.IsHybridAzureDomainJoined
	}
	if o.NetBiosName == nil {
		if o.isExplicitNullNetBiosName {
			toSerialize["netBiosName"] = o.NetBiosName
		}
	} else {
		toSerialize["netBiosName"] = o.NetBiosName
	}
	if o.Os == nil {
		if o.isExplicitNullOs {
			toSerialize["os"] = o.Os
		}
	} else {
		toSerialize["os"] = o.Os
	}
	if o.PrivateIpAddress == nil {
		if o.isExplicitNullPrivateIpAddress {
			toSerialize["privateIpAddress"] = o.PrivateIpAddress
		}
	} else {
		toSerialize["privateIpAddress"] = o.PrivateIpAddress
	}
	if o.PublicIpAddress == nil {
		if o.isExplicitNullPublicIpAddress {
			toSerialize["publicIpAddress"] = o.PublicIpAddress
		}
	} else {
		toSerialize["publicIpAddress"] = o.PublicIpAddress
	}
	if o.RiskScore == nil {
		if o.isExplicitNullRiskScore {
			toSerialize["riskScore"] = o.RiskScore
		}
	} else {
		toSerialize["riskScore"] = o.RiskScore
	}
	return json.Marshal(toSerialize)
}


