/*
 * OData Service for namespace microsoft.graph
 *
 * This OData service is located at https://graph.microsoft.com/v1.0/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph
// MicrosoftGraphWindowsUserAccountControlSettings the model 'MicrosoftGraphWindowsUserAccountControlSettings'
type MicrosoftGraphWindowsUserAccountControlSettings string

// List of microsoft.graph.windowsUserAccountControlSettings
const (
	USER_DEFINED MicrosoftGraphWindowsUserAccountControlSettings = "userDefined"
	ALWAYS_NOTIFY MicrosoftGraphWindowsUserAccountControlSettings = "alwaysNotify"
	NOTIFY_ON_APP_CHANGES MicrosoftGraphWindowsUserAccountControlSettings = "notifyOnAppChanges"
	NOTIFY_ON_APP_CHANGES_WITHOUT_DIMMING MicrosoftGraphWindowsUserAccountControlSettings = "notifyOnAppChangesWithoutDimming"
	NEVER_NOTIFY MicrosoftGraphWindowsUserAccountControlSettings = "neverNotify"
)


