/*
 * OData Service for namespace microsoft.graph
 *
 * This OData service is located at https://graph.microsoft.com/v1.0/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph
import (
	"encoding/json"
)
// InlineObject191 struct for InlineObject191
type InlineObject191 struct {
	Post *MicrosoftGraphPost `json:"Post,omitempty"`

}

// GetPost returns the Post field if non-nil, zero value otherwise.
func (o *InlineObject191) GetPost() MicrosoftGraphPost {
	if o == nil || o.Post == nil {
		var ret MicrosoftGraphPost
		return ret
	}
	return *o.Post
}

// GetPostOk returns a tuple with the Post field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject191) GetPostOk() (MicrosoftGraphPost, bool) {
	if o == nil || o.Post == nil {
		var ret MicrosoftGraphPost
		return ret, false
	}
	return *o.Post, true
}

// HasPost returns a boolean if a field has been set.
func (o *InlineObject191) HasPost() bool {
	if o != nil && o.Post != nil {
		return true
	}

	return false
}

// SetPost gets a reference to the given MicrosoftGraphPost and assigns it to the Post field.
func (o *InlineObject191) SetPost(v MicrosoftGraphPost) {
	o.Post = &v
}


// MarshalJSON returns the JSON representation of the model.
func (o InlineObject191) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Post != nil {
		toSerialize["Post"] = o.Post
	}
	return json.Marshal(toSerialize)
}


