/*
 * OData Service for namespace microsoft.graph
 *
 * This OData service is located at https://graph.microsoft.com/v1.0/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph
// MicrosoftGraphRatingAppsType the model 'MicrosoftGraphRatingAppsType'
type MicrosoftGraphRatingAppsType string

// List of microsoft.graph.ratingAppsType
const (
	ALL_ALLOWED MicrosoftGraphRatingAppsType = "allAllowed"
	ALL_BLOCKED MicrosoftGraphRatingAppsType = "allBlocked"
	AGES_ABOVE4 MicrosoftGraphRatingAppsType = "agesAbove4"
	AGES_ABOVE9 MicrosoftGraphRatingAppsType = "agesAbove9"
	AGES_ABOVE12 MicrosoftGraphRatingAppsType = "agesAbove12"
	AGES_ABOVE17 MicrosoftGraphRatingAppsType = "agesAbove17"
)


