/*
 * OData Service for namespace microsoft.graph
 *
 * This OData service is located at https://graph.microsoft.com/v1.0/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph
import (
	"encoding/json"
)
// MicrosoftGraphAutomaticRepliesMailTips struct for MicrosoftGraphAutomaticRepliesMailTips
type MicrosoftGraphAutomaticRepliesMailTips struct {
	Message *string `json:"message,omitempty"`
	isExplicitNullMessage bool `json:"-"`
	MessageLanguage *AnyOfmicrosoftGraphLocaleInfo `json:"messageLanguage,omitempty"`
	isExplicitNullMessageLanguage bool `json:"-"`
	ScheduledStartTime *AnyOfmicrosoftGraphDateTimeTimeZone `json:"scheduledStartTime,omitempty"`
	isExplicitNullScheduledStartTime bool `json:"-"`
	ScheduledEndTime *AnyOfmicrosoftGraphDateTimeTimeZone `json:"scheduledEndTime,omitempty"`
	isExplicitNullScheduledEndTime bool `json:"-"`
}

// GetMessage returns the Message field if non-nil, zero value otherwise.
func (o *MicrosoftGraphAutomaticRepliesMailTips) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphAutomaticRepliesMailTips) GetMessageOk() (string, bool) {
	if o == nil || o.Message == nil {
		var ret string
		return ret, false
	}
	return *o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *MicrosoftGraphAutomaticRepliesMailTips) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *MicrosoftGraphAutomaticRepliesMailTips) SetMessage(v string) {
	o.Message = &v
}

// SetMessageExplicitNull (un)sets Message to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The Message value is set to nil even if false is passed
func (o *MicrosoftGraphAutomaticRepliesMailTips) SetMessageExplicitNull(b bool) {
	o.Message = nil
	o.isExplicitNullMessage = b
}
// GetMessageLanguage returns the MessageLanguage field if non-nil, zero value otherwise.
func (o *MicrosoftGraphAutomaticRepliesMailTips) GetMessageLanguage() AnyOfmicrosoftGraphLocaleInfo {
	if o == nil || o.MessageLanguage == nil {
		var ret AnyOfmicrosoftGraphLocaleInfo
		return ret
	}
	return *o.MessageLanguage
}

// GetMessageLanguageOk returns a tuple with the MessageLanguage field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphAutomaticRepliesMailTips) GetMessageLanguageOk() (AnyOfmicrosoftGraphLocaleInfo, bool) {
	if o == nil || o.MessageLanguage == nil {
		var ret AnyOfmicrosoftGraphLocaleInfo
		return ret, false
	}
	return *o.MessageLanguage, true
}

// HasMessageLanguage returns a boolean if a field has been set.
func (o *MicrosoftGraphAutomaticRepliesMailTips) HasMessageLanguage() bool {
	if o != nil && o.MessageLanguage != nil {
		return true
	}

	return false
}

// SetMessageLanguage gets a reference to the given AnyOfmicrosoftGraphLocaleInfo and assigns it to the MessageLanguage field.
func (o *MicrosoftGraphAutomaticRepliesMailTips) SetMessageLanguage(v AnyOfmicrosoftGraphLocaleInfo) {
	o.MessageLanguage = &v
}

// SetMessageLanguageExplicitNull (un)sets MessageLanguage to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The MessageLanguage value is set to nil even if false is passed
func (o *MicrosoftGraphAutomaticRepliesMailTips) SetMessageLanguageExplicitNull(b bool) {
	o.MessageLanguage = nil
	o.isExplicitNullMessageLanguage = b
}
// GetScheduledStartTime returns the ScheduledStartTime field if non-nil, zero value otherwise.
func (o *MicrosoftGraphAutomaticRepliesMailTips) GetScheduledStartTime() AnyOfmicrosoftGraphDateTimeTimeZone {
	if o == nil || o.ScheduledStartTime == nil {
		var ret AnyOfmicrosoftGraphDateTimeTimeZone
		return ret
	}
	return *o.ScheduledStartTime
}

// GetScheduledStartTimeOk returns a tuple with the ScheduledStartTime field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphAutomaticRepliesMailTips) GetScheduledStartTimeOk() (AnyOfmicrosoftGraphDateTimeTimeZone, bool) {
	if o == nil || o.ScheduledStartTime == nil {
		var ret AnyOfmicrosoftGraphDateTimeTimeZone
		return ret, false
	}
	return *o.ScheduledStartTime, true
}

// HasScheduledStartTime returns a boolean if a field has been set.
func (o *MicrosoftGraphAutomaticRepliesMailTips) HasScheduledStartTime() bool {
	if o != nil && o.ScheduledStartTime != nil {
		return true
	}

	return false
}

// SetScheduledStartTime gets a reference to the given AnyOfmicrosoftGraphDateTimeTimeZone and assigns it to the ScheduledStartTime field.
func (o *MicrosoftGraphAutomaticRepliesMailTips) SetScheduledStartTime(v AnyOfmicrosoftGraphDateTimeTimeZone) {
	o.ScheduledStartTime = &v
}

// SetScheduledStartTimeExplicitNull (un)sets ScheduledStartTime to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The ScheduledStartTime value is set to nil even if false is passed
func (o *MicrosoftGraphAutomaticRepliesMailTips) SetScheduledStartTimeExplicitNull(b bool) {
	o.ScheduledStartTime = nil
	o.isExplicitNullScheduledStartTime = b
}
// GetScheduledEndTime returns the ScheduledEndTime field if non-nil, zero value otherwise.
func (o *MicrosoftGraphAutomaticRepliesMailTips) GetScheduledEndTime() AnyOfmicrosoftGraphDateTimeTimeZone {
	if o == nil || o.ScheduledEndTime == nil {
		var ret AnyOfmicrosoftGraphDateTimeTimeZone
		return ret
	}
	return *o.ScheduledEndTime
}

// GetScheduledEndTimeOk returns a tuple with the ScheduledEndTime field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphAutomaticRepliesMailTips) GetScheduledEndTimeOk() (AnyOfmicrosoftGraphDateTimeTimeZone, bool) {
	if o == nil || o.ScheduledEndTime == nil {
		var ret AnyOfmicrosoftGraphDateTimeTimeZone
		return ret, false
	}
	return *o.ScheduledEndTime, true
}

// HasScheduledEndTime returns a boolean if a field has been set.
func (o *MicrosoftGraphAutomaticRepliesMailTips) HasScheduledEndTime() bool {
	if o != nil && o.ScheduledEndTime != nil {
		return true
	}

	return false
}

// SetScheduledEndTime gets a reference to the given AnyOfmicrosoftGraphDateTimeTimeZone and assigns it to the ScheduledEndTime field.
func (o *MicrosoftGraphAutomaticRepliesMailTips) SetScheduledEndTime(v AnyOfmicrosoftGraphDateTimeTimeZone) {
	o.ScheduledEndTime = &v
}

// SetScheduledEndTimeExplicitNull (un)sets ScheduledEndTime to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The ScheduledEndTime value is set to nil even if false is passed
func (o *MicrosoftGraphAutomaticRepliesMailTips) SetScheduledEndTimeExplicitNull(b bool) {
	o.ScheduledEndTime = nil
	o.isExplicitNullScheduledEndTime = b
}

// MarshalJSON returns the JSON representation of the model.
func (o MicrosoftGraphAutomaticRepliesMailTips) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Message == nil {
		if o.isExplicitNullMessage {
			toSerialize["message"] = o.Message
		}
	} else {
		toSerialize["message"] = o.Message
	}
	if o.MessageLanguage == nil {
		if o.isExplicitNullMessageLanguage {
			toSerialize["messageLanguage"] = o.MessageLanguage
		}
	} else {
		toSerialize["messageLanguage"] = o.MessageLanguage
	}
	if o.ScheduledStartTime == nil {
		if o.isExplicitNullScheduledStartTime {
			toSerialize["scheduledStartTime"] = o.ScheduledStartTime
		}
	} else {
		toSerialize["scheduledStartTime"] = o.ScheduledStartTime
	}
	if o.ScheduledEndTime == nil {
		if o.isExplicitNullScheduledEndTime {
			toSerialize["scheduledEndTime"] = o.ScheduledEndTime
		}
	} else {
		toSerialize["scheduledEndTime"] = o.ScheduledEndTime
	}
	return json.Marshal(toSerialize)
}


