/*
 * OData Service for namespace microsoft.graph
 *
 * This OData service is located at https://graph.microsoft.com/v1.0/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph
import (
	"time"
	"encoding/json"
)
// MicrosoftGraphUserSecurityState struct for MicrosoftGraphUserSecurityState
type MicrosoftGraphUserSecurityState struct {
	AadUserId *string `json:"aadUserId,omitempty"`
	isExplicitNullAadUserId bool `json:"-"`
	AccountName *string `json:"accountName,omitempty"`
	isExplicitNullAccountName bool `json:"-"`
	DomainName *string `json:"domainName,omitempty"`
	isExplicitNullDomainName bool `json:"-"`
	EmailRole *AnyOfmicrosoftGraphEmailRole `json:"emailRole,omitempty"`
	isExplicitNullEmailRole bool `json:"-"`
	IsVpn *bool `json:"isVpn,omitempty"`
	isExplicitNullIsVpn bool `json:"-"`
	LogonDateTime *time.Time `json:"logonDateTime,omitempty"`
	isExplicitNullLogonDateTime bool `json:"-"`
	LogonId *string `json:"logonId,omitempty"`
	isExplicitNullLogonId bool `json:"-"`
	LogonIp *string `json:"logonIp,omitempty"`
	isExplicitNullLogonIp bool `json:"-"`
	LogonLocation *string `json:"logonLocation,omitempty"`
	isExplicitNullLogonLocation bool `json:"-"`
	LogonType *AnyOfmicrosoftGraphLogonType `json:"logonType,omitempty"`
	isExplicitNullLogonType bool `json:"-"`
	OnPremisesSecurityIdentifier *string `json:"onPremisesSecurityIdentifier,omitempty"`
	isExplicitNullOnPremisesSecurityIdentifier bool `json:"-"`
	RiskScore *string `json:"riskScore,omitempty"`
	isExplicitNullRiskScore bool `json:"-"`
	UserAccountType *AnyOfmicrosoftGraphUserAccountSecurityType `json:"userAccountType,omitempty"`
	isExplicitNullUserAccountType bool `json:"-"`
	UserPrincipalName *string `json:"userPrincipalName,omitempty"`
	isExplicitNullUserPrincipalName bool `json:"-"`
}

// GetAadUserId returns the AadUserId field if non-nil, zero value otherwise.
func (o *MicrosoftGraphUserSecurityState) GetAadUserId() string {
	if o == nil || o.AadUserId == nil {
		var ret string
		return ret
	}
	return *o.AadUserId
}

// GetAadUserIdOk returns a tuple with the AadUserId field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphUserSecurityState) GetAadUserIdOk() (string, bool) {
	if o == nil || o.AadUserId == nil {
		var ret string
		return ret, false
	}
	return *o.AadUserId, true
}

// HasAadUserId returns a boolean if a field has been set.
func (o *MicrosoftGraphUserSecurityState) HasAadUserId() bool {
	if o != nil && o.AadUserId != nil {
		return true
	}

	return false
}

// SetAadUserId gets a reference to the given string and assigns it to the AadUserId field.
func (o *MicrosoftGraphUserSecurityState) SetAadUserId(v string) {
	o.AadUserId = &v
}

// SetAadUserIdExplicitNull (un)sets AadUserId to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The AadUserId value is set to nil even if false is passed
func (o *MicrosoftGraphUserSecurityState) SetAadUserIdExplicitNull(b bool) {
	o.AadUserId = nil
	o.isExplicitNullAadUserId = b
}
// GetAccountName returns the AccountName field if non-nil, zero value otherwise.
func (o *MicrosoftGraphUserSecurityState) GetAccountName() string {
	if o == nil || o.AccountName == nil {
		var ret string
		return ret
	}
	return *o.AccountName
}

// GetAccountNameOk returns a tuple with the AccountName field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphUserSecurityState) GetAccountNameOk() (string, bool) {
	if o == nil || o.AccountName == nil {
		var ret string
		return ret, false
	}
	return *o.AccountName, true
}

// HasAccountName returns a boolean if a field has been set.
func (o *MicrosoftGraphUserSecurityState) HasAccountName() bool {
	if o != nil && o.AccountName != nil {
		return true
	}

	return false
}

// SetAccountName gets a reference to the given string and assigns it to the AccountName field.
func (o *MicrosoftGraphUserSecurityState) SetAccountName(v string) {
	o.AccountName = &v
}

// SetAccountNameExplicitNull (un)sets AccountName to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The AccountName value is set to nil even if false is passed
func (o *MicrosoftGraphUserSecurityState) SetAccountNameExplicitNull(b bool) {
	o.AccountName = nil
	o.isExplicitNullAccountName = b
}
// GetDomainName returns the DomainName field if non-nil, zero value otherwise.
func (o *MicrosoftGraphUserSecurityState) GetDomainName() string {
	if o == nil || o.DomainName == nil {
		var ret string
		return ret
	}
	return *o.DomainName
}

// GetDomainNameOk returns a tuple with the DomainName field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphUserSecurityState) GetDomainNameOk() (string, bool) {
	if o == nil || o.DomainName == nil {
		var ret string
		return ret, false
	}
	return *o.DomainName, true
}

// HasDomainName returns a boolean if a field has been set.
func (o *MicrosoftGraphUserSecurityState) HasDomainName() bool {
	if o != nil && o.DomainName != nil {
		return true
	}

	return false
}

// SetDomainName gets a reference to the given string and assigns it to the DomainName field.
func (o *MicrosoftGraphUserSecurityState) SetDomainName(v string) {
	o.DomainName = &v
}

// SetDomainNameExplicitNull (un)sets DomainName to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The DomainName value is set to nil even if false is passed
func (o *MicrosoftGraphUserSecurityState) SetDomainNameExplicitNull(b bool) {
	o.DomainName = nil
	o.isExplicitNullDomainName = b
}
// GetEmailRole returns the EmailRole field if non-nil, zero value otherwise.
func (o *MicrosoftGraphUserSecurityState) GetEmailRole() AnyOfmicrosoftGraphEmailRole {
	if o == nil || o.EmailRole == nil {
		var ret AnyOfmicrosoftGraphEmailRole
		return ret
	}
	return *o.EmailRole
}

// GetEmailRoleOk returns a tuple with the EmailRole field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphUserSecurityState) GetEmailRoleOk() (AnyOfmicrosoftGraphEmailRole, bool) {
	if o == nil || o.EmailRole == nil {
		var ret AnyOfmicrosoftGraphEmailRole
		return ret, false
	}
	return *o.EmailRole, true
}

// HasEmailRole returns a boolean if a field has been set.
func (o *MicrosoftGraphUserSecurityState) HasEmailRole() bool {
	if o != nil && o.EmailRole != nil {
		return true
	}

	return false
}

// SetEmailRole gets a reference to the given AnyOfmicrosoftGraphEmailRole and assigns it to the EmailRole field.
func (o *MicrosoftGraphUserSecurityState) SetEmailRole(v AnyOfmicrosoftGraphEmailRole) {
	o.EmailRole = &v
}

// SetEmailRoleExplicitNull (un)sets EmailRole to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The EmailRole value is set to nil even if false is passed
func (o *MicrosoftGraphUserSecurityState) SetEmailRoleExplicitNull(b bool) {
	o.EmailRole = nil
	o.isExplicitNullEmailRole = b
}
// GetIsVpn returns the IsVpn field if non-nil, zero value otherwise.
func (o *MicrosoftGraphUserSecurityState) GetIsVpn() bool {
	if o == nil || o.IsVpn == nil {
		var ret bool
		return ret
	}
	return *o.IsVpn
}

// GetIsVpnOk returns a tuple with the IsVpn field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphUserSecurityState) GetIsVpnOk() (bool, bool) {
	if o == nil || o.IsVpn == nil {
		var ret bool
		return ret, false
	}
	return *o.IsVpn, true
}

// HasIsVpn returns a boolean if a field has been set.
func (o *MicrosoftGraphUserSecurityState) HasIsVpn() bool {
	if o != nil && o.IsVpn != nil {
		return true
	}

	return false
}

// SetIsVpn gets a reference to the given bool and assigns it to the IsVpn field.
func (o *MicrosoftGraphUserSecurityState) SetIsVpn(v bool) {
	o.IsVpn = &v
}

// SetIsVpnExplicitNull (un)sets IsVpn to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The IsVpn value is set to nil even if false is passed
func (o *MicrosoftGraphUserSecurityState) SetIsVpnExplicitNull(b bool) {
	o.IsVpn = nil
	o.isExplicitNullIsVpn = b
}
// GetLogonDateTime returns the LogonDateTime field if non-nil, zero value otherwise.
func (o *MicrosoftGraphUserSecurityState) GetLogonDateTime() time.Time {
	if o == nil || o.LogonDateTime == nil {
		var ret time.Time
		return ret
	}
	return *o.LogonDateTime
}

// GetLogonDateTimeOk returns a tuple with the LogonDateTime field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphUserSecurityState) GetLogonDateTimeOk() (time.Time, bool) {
	if o == nil || o.LogonDateTime == nil {
		var ret time.Time
		return ret, false
	}
	return *o.LogonDateTime, true
}

// HasLogonDateTime returns a boolean if a field has been set.
func (o *MicrosoftGraphUserSecurityState) HasLogonDateTime() bool {
	if o != nil && o.LogonDateTime != nil {
		return true
	}

	return false
}

// SetLogonDateTime gets a reference to the given time.Time and assigns it to the LogonDateTime field.
func (o *MicrosoftGraphUserSecurityState) SetLogonDateTime(v time.Time) {
	o.LogonDateTime = &v
}

// SetLogonDateTimeExplicitNull (un)sets LogonDateTime to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The LogonDateTime value is set to nil even if false is passed
func (o *MicrosoftGraphUserSecurityState) SetLogonDateTimeExplicitNull(b bool) {
	o.LogonDateTime = nil
	o.isExplicitNullLogonDateTime = b
}
// GetLogonId returns the LogonId field if non-nil, zero value otherwise.
func (o *MicrosoftGraphUserSecurityState) GetLogonId() string {
	if o == nil || o.LogonId == nil {
		var ret string
		return ret
	}
	return *o.LogonId
}

// GetLogonIdOk returns a tuple with the LogonId field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphUserSecurityState) GetLogonIdOk() (string, bool) {
	if o == nil || o.LogonId == nil {
		var ret string
		return ret, false
	}
	return *o.LogonId, true
}

// HasLogonId returns a boolean if a field has been set.
func (o *MicrosoftGraphUserSecurityState) HasLogonId() bool {
	if o != nil && o.LogonId != nil {
		return true
	}

	return false
}

// SetLogonId gets a reference to the given string and assigns it to the LogonId field.
func (o *MicrosoftGraphUserSecurityState) SetLogonId(v string) {
	o.LogonId = &v
}

// SetLogonIdExplicitNull (un)sets LogonId to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The LogonId value is set to nil even if false is passed
func (o *MicrosoftGraphUserSecurityState) SetLogonIdExplicitNull(b bool) {
	o.LogonId = nil
	o.isExplicitNullLogonId = b
}
// GetLogonIp returns the LogonIp field if non-nil, zero value otherwise.
func (o *MicrosoftGraphUserSecurityState) GetLogonIp() string {
	if o == nil || o.LogonIp == nil {
		var ret string
		return ret
	}
	return *o.LogonIp
}

// GetLogonIpOk returns a tuple with the LogonIp field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphUserSecurityState) GetLogonIpOk() (string, bool) {
	if o == nil || o.LogonIp == nil {
		var ret string
		return ret, false
	}
	return *o.LogonIp, true
}

// HasLogonIp returns a boolean if a field has been set.
func (o *MicrosoftGraphUserSecurityState) HasLogonIp() bool {
	if o != nil && o.LogonIp != nil {
		return true
	}

	return false
}

// SetLogonIp gets a reference to the given string and assigns it to the LogonIp field.
func (o *MicrosoftGraphUserSecurityState) SetLogonIp(v string) {
	o.LogonIp = &v
}

// SetLogonIpExplicitNull (un)sets LogonIp to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The LogonIp value is set to nil even if false is passed
func (o *MicrosoftGraphUserSecurityState) SetLogonIpExplicitNull(b bool) {
	o.LogonIp = nil
	o.isExplicitNullLogonIp = b
}
// GetLogonLocation returns the LogonLocation field if non-nil, zero value otherwise.
func (o *MicrosoftGraphUserSecurityState) GetLogonLocation() string {
	if o == nil || o.LogonLocation == nil {
		var ret string
		return ret
	}
	return *o.LogonLocation
}

// GetLogonLocationOk returns a tuple with the LogonLocation field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphUserSecurityState) GetLogonLocationOk() (string, bool) {
	if o == nil || o.LogonLocation == nil {
		var ret string
		return ret, false
	}
	return *o.LogonLocation, true
}

// HasLogonLocation returns a boolean if a field has been set.
func (o *MicrosoftGraphUserSecurityState) HasLogonLocation() bool {
	if o != nil && o.LogonLocation != nil {
		return true
	}

	return false
}

// SetLogonLocation gets a reference to the given string and assigns it to the LogonLocation field.
func (o *MicrosoftGraphUserSecurityState) SetLogonLocation(v string) {
	o.LogonLocation = &v
}

// SetLogonLocationExplicitNull (un)sets LogonLocation to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The LogonLocation value is set to nil even if false is passed
func (o *MicrosoftGraphUserSecurityState) SetLogonLocationExplicitNull(b bool) {
	o.LogonLocation = nil
	o.isExplicitNullLogonLocation = b
}
// GetLogonType returns the LogonType field if non-nil, zero value otherwise.
func (o *MicrosoftGraphUserSecurityState) GetLogonType() AnyOfmicrosoftGraphLogonType {
	if o == nil || o.LogonType == nil {
		var ret AnyOfmicrosoftGraphLogonType
		return ret
	}
	return *o.LogonType
}

// GetLogonTypeOk returns a tuple with the LogonType field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphUserSecurityState) GetLogonTypeOk() (AnyOfmicrosoftGraphLogonType, bool) {
	if o == nil || o.LogonType == nil {
		var ret AnyOfmicrosoftGraphLogonType
		return ret, false
	}
	return *o.LogonType, true
}

// HasLogonType returns a boolean if a field has been set.
func (o *MicrosoftGraphUserSecurityState) HasLogonType() bool {
	if o != nil && o.LogonType != nil {
		return true
	}

	return false
}

// SetLogonType gets a reference to the given AnyOfmicrosoftGraphLogonType and assigns it to the LogonType field.
func (o *MicrosoftGraphUserSecurityState) SetLogonType(v AnyOfmicrosoftGraphLogonType) {
	o.LogonType = &v
}

// SetLogonTypeExplicitNull (un)sets LogonType to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The LogonType value is set to nil even if false is passed
func (o *MicrosoftGraphUserSecurityState) SetLogonTypeExplicitNull(b bool) {
	o.LogonType = nil
	o.isExplicitNullLogonType = b
}
// GetOnPremisesSecurityIdentifier returns the OnPremisesSecurityIdentifier field if non-nil, zero value otherwise.
func (o *MicrosoftGraphUserSecurityState) GetOnPremisesSecurityIdentifier() string {
	if o == nil || o.OnPremisesSecurityIdentifier == nil {
		var ret string
		return ret
	}
	return *o.OnPremisesSecurityIdentifier
}

// GetOnPremisesSecurityIdentifierOk returns a tuple with the OnPremisesSecurityIdentifier field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphUserSecurityState) GetOnPremisesSecurityIdentifierOk() (string, bool) {
	if o == nil || o.OnPremisesSecurityIdentifier == nil {
		var ret string
		return ret, false
	}
	return *o.OnPremisesSecurityIdentifier, true
}

// HasOnPremisesSecurityIdentifier returns a boolean if a field has been set.
func (o *MicrosoftGraphUserSecurityState) HasOnPremisesSecurityIdentifier() bool {
	if o != nil && o.OnPremisesSecurityIdentifier != nil {
		return true
	}

	return false
}

// SetOnPremisesSecurityIdentifier gets a reference to the given string and assigns it to the OnPremisesSecurityIdentifier field.
func (o *MicrosoftGraphUserSecurityState) SetOnPremisesSecurityIdentifier(v string) {
	o.OnPremisesSecurityIdentifier = &v
}

// SetOnPremisesSecurityIdentifierExplicitNull (un)sets OnPremisesSecurityIdentifier to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The OnPremisesSecurityIdentifier value is set to nil even if false is passed
func (o *MicrosoftGraphUserSecurityState) SetOnPremisesSecurityIdentifierExplicitNull(b bool) {
	o.OnPremisesSecurityIdentifier = nil
	o.isExplicitNullOnPremisesSecurityIdentifier = b
}
// GetRiskScore returns the RiskScore field if non-nil, zero value otherwise.
func (o *MicrosoftGraphUserSecurityState) GetRiskScore() string {
	if o == nil || o.RiskScore == nil {
		var ret string
		return ret
	}
	return *o.RiskScore
}

// GetRiskScoreOk returns a tuple with the RiskScore field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphUserSecurityState) GetRiskScoreOk() (string, bool) {
	if o == nil || o.RiskScore == nil {
		var ret string
		return ret, false
	}
	return *o.RiskScore, true
}

// HasRiskScore returns a boolean if a field has been set.
func (o *MicrosoftGraphUserSecurityState) HasRiskScore() bool {
	if o != nil && o.RiskScore != nil {
		return true
	}

	return false
}

// SetRiskScore gets a reference to the given string and assigns it to the RiskScore field.
func (o *MicrosoftGraphUserSecurityState) SetRiskScore(v string) {
	o.RiskScore = &v
}

// SetRiskScoreExplicitNull (un)sets RiskScore to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The RiskScore value is set to nil even if false is passed
func (o *MicrosoftGraphUserSecurityState) SetRiskScoreExplicitNull(b bool) {
	o.RiskScore = nil
	o.isExplicitNullRiskScore = b
}
// GetUserAccountType returns the UserAccountType field if non-nil, zero value otherwise.
func (o *MicrosoftGraphUserSecurityState) GetUserAccountType() AnyOfmicrosoftGraphUserAccountSecurityType {
	if o == nil || o.UserAccountType == nil {
		var ret AnyOfmicrosoftGraphUserAccountSecurityType
		return ret
	}
	return *o.UserAccountType
}

// GetUserAccountTypeOk returns a tuple with the UserAccountType field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphUserSecurityState) GetUserAccountTypeOk() (AnyOfmicrosoftGraphUserAccountSecurityType, bool) {
	if o == nil || o.UserAccountType == nil {
		var ret AnyOfmicrosoftGraphUserAccountSecurityType
		return ret, false
	}
	return *o.UserAccountType, true
}

// HasUserAccountType returns a boolean if a field has been set.
func (o *MicrosoftGraphUserSecurityState) HasUserAccountType() bool {
	if o != nil && o.UserAccountType != nil {
		return true
	}

	return false
}

// SetUserAccountType gets a reference to the given AnyOfmicrosoftGraphUserAccountSecurityType and assigns it to the UserAccountType field.
func (o *MicrosoftGraphUserSecurityState) SetUserAccountType(v AnyOfmicrosoftGraphUserAccountSecurityType) {
	o.UserAccountType = &v
}

// SetUserAccountTypeExplicitNull (un)sets UserAccountType to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The UserAccountType value is set to nil even if false is passed
func (o *MicrosoftGraphUserSecurityState) SetUserAccountTypeExplicitNull(b bool) {
	o.UserAccountType = nil
	o.isExplicitNullUserAccountType = b
}
// GetUserPrincipalName returns the UserPrincipalName field if non-nil, zero value otherwise.
func (o *MicrosoftGraphUserSecurityState) GetUserPrincipalName() string {
	if o == nil || o.UserPrincipalName == nil {
		var ret string
		return ret
	}
	return *o.UserPrincipalName
}

// GetUserPrincipalNameOk returns a tuple with the UserPrincipalName field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphUserSecurityState) GetUserPrincipalNameOk() (string, bool) {
	if o == nil || o.UserPrincipalName == nil {
		var ret string
		return ret, false
	}
	return *o.UserPrincipalName, true
}

// HasUserPrincipalName returns a boolean if a field has been set.
func (o *MicrosoftGraphUserSecurityState) HasUserPrincipalName() bool {
	if o != nil && o.UserPrincipalName != nil {
		return true
	}

	return false
}

// SetUserPrincipalName gets a reference to the given string and assigns it to the UserPrincipalName field.
func (o *MicrosoftGraphUserSecurityState) SetUserPrincipalName(v string) {
	o.UserPrincipalName = &v
}

// SetUserPrincipalNameExplicitNull (un)sets UserPrincipalName to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The UserPrincipalName value is set to nil even if false is passed
func (o *MicrosoftGraphUserSecurityState) SetUserPrincipalNameExplicitNull(b bool) {
	o.UserPrincipalName = nil
	o.isExplicitNullUserPrincipalName = b
}

// MarshalJSON returns the JSON representation of the model.
func (o MicrosoftGraphUserSecurityState) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AadUserId == nil {
		if o.isExplicitNullAadUserId {
			toSerialize["aadUserId"] = o.AadUserId
		}
	} else {
		toSerialize["aadUserId"] = o.AadUserId
	}
	if o.AccountName == nil {
		if o.isExplicitNullAccountName {
			toSerialize["accountName"] = o.AccountName
		}
	} else {
		toSerialize["accountName"] = o.AccountName
	}
	if o.DomainName == nil {
		if o.isExplicitNullDomainName {
			toSerialize["domainName"] = o.DomainName
		}
	} else {
		toSerialize["domainName"] = o.DomainName
	}
	if o.EmailRole == nil {
		if o.isExplicitNullEmailRole {
			toSerialize["emailRole"] = o.EmailRole
		}
	} else {
		toSerialize["emailRole"] = o.EmailRole
	}
	if o.IsVpn == nil {
		if o.isExplicitNullIsVpn {
			toSerialize["isVpn"] = o.IsVpn
		}
	} else {
		toSerialize["isVpn"] = o.IsVpn
	}
	if o.LogonDateTime == nil {
		if o.isExplicitNullLogonDateTime {
			toSerialize["logonDateTime"] = o.LogonDateTime
		}
	} else {
		toSerialize["logonDateTime"] = o.LogonDateTime
	}
	if o.LogonId == nil {
		if o.isExplicitNullLogonId {
			toSerialize["logonId"] = o.LogonId
		}
	} else {
		toSerialize["logonId"] = o.LogonId
	}
	if o.LogonIp == nil {
		if o.isExplicitNullLogonIp {
			toSerialize["logonIp"] = o.LogonIp
		}
	} else {
		toSerialize["logonIp"] = o.LogonIp
	}
	if o.LogonLocation == nil {
		if o.isExplicitNullLogonLocation {
			toSerialize["logonLocation"] = o.LogonLocation
		}
	} else {
		toSerialize["logonLocation"] = o.LogonLocation
	}
	if o.LogonType == nil {
		if o.isExplicitNullLogonType {
			toSerialize["logonType"] = o.LogonType
		}
	} else {
		toSerialize["logonType"] = o.LogonType
	}
	if o.OnPremisesSecurityIdentifier == nil {
		if o.isExplicitNullOnPremisesSecurityIdentifier {
			toSerialize["onPremisesSecurityIdentifier"] = o.OnPremisesSecurityIdentifier
		}
	} else {
		toSerialize["onPremisesSecurityIdentifier"] = o.OnPremisesSecurityIdentifier
	}
	if o.RiskScore == nil {
		if o.isExplicitNullRiskScore {
			toSerialize["riskScore"] = o.RiskScore
		}
	} else {
		toSerialize["riskScore"] = o.RiskScore
	}
	if o.UserAccountType == nil {
		if o.isExplicitNullUserAccountType {
			toSerialize["userAccountType"] = o.UserAccountType
		}
	} else {
		toSerialize["userAccountType"] = o.UserAccountType
	}
	if o.UserPrincipalName == nil {
		if o.isExplicitNullUserPrincipalName {
			toSerialize["userPrincipalName"] = o.UserPrincipalName
		}
	} else {
		toSerialize["userPrincipalName"] = o.UserPrincipalName
	}
	return json.Marshal(toSerialize)
}


