/*
 * OData Service for namespace microsoft.graph
 *
 * This OData service is located at https://graph.microsoft.com/v1.0/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph
import (
	"encoding/json"
)
// MicrosoftGraphPublicationFacet struct for MicrosoftGraphPublicationFacet
type MicrosoftGraphPublicationFacet struct {
	Level *string `json:"level,omitempty"`
	isExplicitNullLevel bool `json:"-"`
	VersionId *string `json:"versionId,omitempty"`
	isExplicitNullVersionId bool `json:"-"`
}

// GetLevel returns the Level field if non-nil, zero value otherwise.
func (o *MicrosoftGraphPublicationFacet) GetLevel() string {
	if o == nil || o.Level == nil {
		var ret string
		return ret
	}
	return *o.Level
}

// GetLevelOk returns a tuple with the Level field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphPublicationFacet) GetLevelOk() (string, bool) {
	if o == nil || o.Level == nil {
		var ret string
		return ret, false
	}
	return *o.Level, true
}

// HasLevel returns a boolean if a field has been set.
func (o *MicrosoftGraphPublicationFacet) HasLevel() bool {
	if o != nil && o.Level != nil {
		return true
	}

	return false
}

// SetLevel gets a reference to the given string and assigns it to the Level field.
func (o *MicrosoftGraphPublicationFacet) SetLevel(v string) {
	o.Level = &v
}

// SetLevelExplicitNull (un)sets Level to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The Level value is set to nil even if false is passed
func (o *MicrosoftGraphPublicationFacet) SetLevelExplicitNull(b bool) {
	o.Level = nil
	o.isExplicitNullLevel = b
}
// GetVersionId returns the VersionId field if non-nil, zero value otherwise.
func (o *MicrosoftGraphPublicationFacet) GetVersionId() string {
	if o == nil || o.VersionId == nil {
		var ret string
		return ret
	}
	return *o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphPublicationFacet) GetVersionIdOk() (string, bool) {
	if o == nil || o.VersionId == nil {
		var ret string
		return ret, false
	}
	return *o.VersionId, true
}

// HasVersionId returns a boolean if a field has been set.
func (o *MicrosoftGraphPublicationFacet) HasVersionId() bool {
	if o != nil && o.VersionId != nil {
		return true
	}

	return false
}

// SetVersionId gets a reference to the given string and assigns it to the VersionId field.
func (o *MicrosoftGraphPublicationFacet) SetVersionId(v string) {
	o.VersionId = &v
}

// SetVersionIdExplicitNull (un)sets VersionId to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The VersionId value is set to nil even if false is passed
func (o *MicrosoftGraphPublicationFacet) SetVersionIdExplicitNull(b bool) {
	o.VersionId = nil
	o.isExplicitNullVersionId = b
}

// MarshalJSON returns the JSON representation of the model.
func (o MicrosoftGraphPublicationFacet) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Level == nil {
		if o.isExplicitNullLevel {
			toSerialize["level"] = o.Level
		}
	} else {
		toSerialize["level"] = o.Level
	}
	if o.VersionId == nil {
		if o.isExplicitNullVersionId {
			toSerialize["versionId"] = o.VersionId
		}
	} else {
		toSerialize["versionId"] = o.VersionId
	}
	return json.Marshal(toSerialize)
}


