/*
 * OData Service for namespace microsoft.graph
 *
 * This OData service is located at https://graph.microsoft.com/v1.0/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph
import (
	"encoding/json"
)
// MicrosoftGraphTimeZoneInformation struct for MicrosoftGraphTimeZoneInformation
type MicrosoftGraphTimeZoneInformation struct {
	Alias *string `json:"alias,omitempty"`
	isExplicitNullAlias bool `json:"-"`
	DisplayName *string `json:"displayName,omitempty"`
	isExplicitNullDisplayName bool `json:"-"`
}

// GetAlias returns the Alias field if non-nil, zero value otherwise.
func (o *MicrosoftGraphTimeZoneInformation) GetAlias() string {
	if o == nil || o.Alias == nil {
		var ret string
		return ret
	}
	return *o.Alias
}

// GetAliasOk returns a tuple with the Alias field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphTimeZoneInformation) GetAliasOk() (string, bool) {
	if o == nil || o.Alias == nil {
		var ret string
		return ret, false
	}
	return *o.Alias, true
}

// HasAlias returns a boolean if a field has been set.
func (o *MicrosoftGraphTimeZoneInformation) HasAlias() bool {
	if o != nil && o.Alias != nil {
		return true
	}

	return false
}

// SetAlias gets a reference to the given string and assigns it to the Alias field.
func (o *MicrosoftGraphTimeZoneInformation) SetAlias(v string) {
	o.Alias = &v
}

// SetAliasExplicitNull (un)sets Alias to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The Alias value is set to nil even if false is passed
func (o *MicrosoftGraphTimeZoneInformation) SetAliasExplicitNull(b bool) {
	o.Alias = nil
	o.isExplicitNullAlias = b
}
// GetDisplayName returns the DisplayName field if non-nil, zero value otherwise.
func (o *MicrosoftGraphTimeZoneInformation) GetDisplayName() string {
	if o == nil || o.DisplayName == nil {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphTimeZoneInformation) GetDisplayNameOk() (string, bool) {
	if o == nil || o.DisplayName == nil {
		var ret string
		return ret, false
	}
	return *o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *MicrosoftGraphTimeZoneInformation) HasDisplayName() bool {
	if o != nil && o.DisplayName != nil {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *MicrosoftGraphTimeZoneInformation) SetDisplayName(v string) {
	o.DisplayName = &v
}

// SetDisplayNameExplicitNull (un)sets DisplayName to be considered as explicit "null" value
// when serializing to JSON (pass true as argument to set this, false to unset)
// The DisplayName value is set to nil even if false is passed
func (o *MicrosoftGraphTimeZoneInformation) SetDisplayNameExplicitNull(b bool) {
	o.DisplayName = nil
	o.isExplicitNullDisplayName = b
}

// MarshalJSON returns the JSON representation of the model.
func (o MicrosoftGraphTimeZoneInformation) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Alias == nil {
		if o.isExplicitNullAlias {
			toSerialize["alias"] = o.Alias
		}
	} else {
		toSerialize["alias"] = o.Alias
	}
	if o.DisplayName == nil {
		if o.isExplicitNullDisplayName {
			toSerialize["displayName"] = o.DisplayName
		}
	} else {
		toSerialize["displayName"] = o.DisplayName
	}
	return json.Marshal(toSerialize)
}


