/*
 * OData Service for namespace microsoft.graph
 *
 * This OData service is located at https://graph.microsoft.com/v1.0/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph
// MicrosoftGraphWindowsSpotlightEnablementSettings the model 'MicrosoftGraphWindowsSpotlightEnablementSettings'
type MicrosoftGraphWindowsSpotlightEnablementSettings string

// List of microsoft.graph.windowsSpotlightEnablementSettings
const (
	NOT_CONFIGURED MicrosoftGraphWindowsSpotlightEnablementSettings = "notConfigured"
	DISABLED MicrosoftGraphWindowsSpotlightEnablementSettings = "disabled"
	ENABLED MicrosoftGraphWindowsSpotlightEnablementSettings = "enabled"
)


