/*
 * OData Service for namespace microsoft.graph
 *
 * This OData service is located at https://graph.microsoft.com/v1.0/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph
// MicrosoftGraphRegistryOperation the model 'MicrosoftGraphRegistryOperation'
type MicrosoftGraphRegistryOperation string

// List of microsoft.graph.registryOperation
const (
	UNKNOWN MicrosoftGraphRegistryOperation = "unknown"
	CREATE MicrosoftGraphRegistryOperation = "create"
	MODIFY MicrosoftGraphRegistryOperation = "modify"
	DELETE MicrosoftGraphRegistryOperation = "delete"
	UNKNOWN_FUTURE_VALUE MicrosoftGraphRegistryOperation = "unknownFutureValue"
)


